remote_theme: pages-themes/midnight@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
title: Eterra Pathfinder
description: The Comprehensive-ish Last Epoch Guide for Path of Exile Players
relative_links:
  enabled: true
  collections: true
include:
  - PoE-to-LE-Guide.md
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
