remote_theme: dracula/gh-pages
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
title: Eterra Pathfinder
description: The Comprehensive-ish Last Epoch Guide for Path of Exile Players
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - PoE-to-LE-Guide.md
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
